version: 2
jobs:
  primeiro:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "Funciona"
  segundo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "Ainda funciona"

workflows:
  version: 2
  build:
    jobs:
      - primeiro:
          filters:
            branches:
              only:
              - master
      - segundo:
          requires:
          - primeiro
          filters:
            branches:
              only:
              - master